const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  GONE: 410,
  INTERNAL_SERVER_ERROR: 500,
};

const RESPONSE_MESSAGES = {
  COMMON: {
    REQUIRED_FIELDS: "All fields are required.",
    IMAGE_NOT_FOUND: "Image not found.",
    VIDEO_NOT_FOUND: "Video not found.",
    INTERNAL_SERVER_ERROR: "Something went wrong in the server",
  },
  COURSES: {
    CREATED: "Course created successfully.",
    DELETED: "Course deleted successfully.",
    NOT_FOUND: "Course not found.",
    FOUND: "Course found.",
    UPDATED: "Course updated successfully.",
    CATEGORY_FOUND: "Courses found for the given category.",
    USER_COURSES_NOT_FOUND: "Courses not found for the user.",
    USER_COURSES_FOUND: "Courses found for the user.",
    INVALID_SEARCH_QUERY: "Invalid search query.",
    NO_COURSES_FOUND: "No courses found for the search query.",
    SEARCH_RESULTS: "Search results for query.",
    PAGINATION_RESULTS: "Pagination results.",
    PROGRESS_UPDATED: "Course progress updated.",
    PROGRESS_NOT_FOUND: "Course progress not found.",
    COURSE_PROGRESS: "Course progress details.",
  },
  USERS: {
    SIGNED_UP: "User registration successful.",
    SIGNED_IN: "User signed in successfully.",
    NOT_FOUND: "User not found.",
    FOUND: "User found.",
    NO_DATA_PROVIDED: "No data provided for updating profile.",
    USER_ID_NOT_FOUND: "User ID not found.",
    DETAILS_FETCHED: "User details fetched successfully.",
    EMAIL_NOT_FOUND : "Email not found",
    EMAIL_ALREADY_IN_USE: "Email is already in use.",
    USER_DOES_NOT_EXIST: "User does not exist.",
    INVALID_PASSWORD: "Invalid password.",
    MISSING_TOKEN: "Token is missing.",
    EMAIL_SENT: "Email sent successfully",
    EMAIL_VERIFIED: "Email verified successfully",
    UNVERIFIED_EMAIL: "Email in not verified",
    VERIFICATION_TOKEN_EXPIRED: "Invalid or expired token",
    UNAUTHORIZED: "Unauthorized access.",
    PASSWORD_NOT_MATCH: "Password not match",
    SAME_PASSWORD:
      "Your new password cannot be the same as the current password",
    PASSWORD_UPDATED: "User password updated successfully",
    UPDATED: "User details updated successfully.",
    DELETED: "User account deleted successfully.",
  },
  ENROLLMENTS: {
    ENROLLED: "Enrolled in course successfully.",
    USER_ENROLLED_COURSES: "User's enrolled courses.",
  },
  SECTIONS: {
    CREATED: "Section created successfully.",
    UPDATED: "Section updated successfully.",
    DELETED: "Section deleted successfully.",
    NOT_FOUND: "Section not found.",
    FOUND: "Section found.",
  },
  SUBSECTIONS: {
    CREATED: "Subsection created successfully.",
    UPDATED: "Subsection updated successfully.",
    DELETED: "Subsection deleted successfully.",
    NOT_FOUND: "Subsection not found.",
  },
  RATING_AND_REVIEWS: {
    ADDED: "Rating and review added successfully.",
    COURSE_RATINGS_FOUND: "Course ratings and reviews found.",
    INVALID_FORMAT: "Please provide rating and review in a valid format.",
    COURSE_NOT_FOUND_OR_NO_RATINGS: "Course not found or no ratings available.",
    AVERAGE_RATING: "Average course rating.",
  },
};

export { HTTP_STATUS, RESPONSE_MESSAGES };
